# Use an official lightweight Python image.
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Run a command inside the container: print "Hello, World" to the console
CMD ["python", "-c", "print('Hello, Container')"]